[[main]]
none = "none"

[[main]]
name = "Resume."
pageRef = "posts/resume"
identifier = "CtGQhDj8RK"
weight = 1

[[main]]
name = "Posts."
pageRef = "posts"
identifier = "CfGQhDj8RW"
weight = 2

[[main]]
name = "Github"
pre = "github"
url = "https://github.com/kmanns"
identifier = "2S3xINvKML"
weight = 5

[[main]]
name = "LinkedIn"
pre = "linkedin"
url = "https://www.linkedin.com/in/khalilmanns/"
identifier = "0gbLDhlV8k"
weight = 3

[[main]]
name = "Bluesky"
pre = "bluesky"
url = "https://bsky.app/profile/kmanns.bsky.social"
weight = 4

[[footer]]
none = "none"
